# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gmallard_test_hw01}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["gmallard"]
  s.date = %q{2011-01-11}
  s.description = %q{A test gem destined for gemcutter.org.}
  s.email = %q{allard.guy.m@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/gmallard_test_hw01.rb",
    "test/helper.rb",
    "test/test_gmallard_test_hw01.rb"
  ]
  s.homepage = %q{http://github.com/gmallard/gmallard_test_hw01}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{A short test hello world gem.}
  s.test_files = [
    "test/helper.rb",
    "test/test_gmallard_test_hw01.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

